In [1]:
import torch

print(torch.__version__)

1.7.0


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [4]:
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

### Tensor Types
https://pytorch.org/docs/stable/tensors.html

### Initialized tensor

In [5]:
tensor1 = torch.Tensor([[1,2,3], [4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
tensor1.dtype

torch.float64

### Uninitialized tensor

In [7]:
tensor2 = torch.Tensor(3,3)
tensor2

tensor([[1.4790e-311, 1.4790e-311, 1.4790e-311],
        [1.4790e-311, 1.4790e-311, 1.4790e-311],
        [1.4790e-311, 1.4790e-311, 1.4790e-311]])

In [8]:
tensor1.dtype

torch.float64

### Random initialized tensor

In [9]:
tensor_random = torch.rand(2,3)
tensor_random

tensor([[0.9671, 0.7656, 0.4082],
        [0.7596, 0.8227, 0.3203]])

In [10]:
tensor_random = torch.rand(2,3, dtype=torch.float32)
tensor_random

tensor([[0.2635, 0.0068, 0.6295],
        [0.0400, 0.0339, 0.2757]], dtype=torch.float32)

In [11]:
tensor_random_n = torch.randn(2,3)
tensor_random_n

tensor([[ 0.4700,  0.6561,  0.3258],
        [-0.4588, -1.3015, -1.1325]])

### Integer tensor

In [12]:
tensor_int = torch.Tensor([[1,2,3], [4,5,6]]).type(torch.int)
tensor_int

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

#### Short is equivalent to int16

In [13]:
tensor_short = torch.ShortTensor([[10.0,20.0],[40.0,80.0]])
tensor_short

tensor([[10, 20],
        [40, 80]], dtype=torch.int16)

In [14]:
tensor_half = torch.HalfTensor([11.0,22.0])
tensor_half

tensor([11., 22.], dtype=torch.float16)

In [15]:
tensor_full = torch.full((2,3), fill_value = 10, dtype = torch.int64)
tensor_full

tensor([[10, 10, 10],
        [10, 10, 10]])

In [16]:
tensor_ones = torch.ones_like(tensor_full)
tensor_ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
tensor_zeros = torch.zeros_like(tensor_full)
tensor_zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

### Some more utility functions

In [18]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
tensor_step = torch.linspace(start=1, end=10, steps=5)
tensor_step

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

#### Creating sparse tensor

In [20]:
index = torch.Tensor([[0,1], [1,2]])

In [21]:
values = torch.Tensor([1,5])

In [22]:
tensor_sparse = torch.sparse_coo_tensor(index, values, [2,3])
tensor_sparse.data

tensor(indices=tensor([[0, 1],
                       [1, 2]]),
       values=tensor([1., 5.]),
       size=(2, 3), nnz=2, layout=torch.sparse_coo)

In [23]:
tensor_dense = tensor_sparse.to_dense()
tensor_dense

tensor([[0., 1., 0.],
        [0., 0., 5.]])

## Operations on tensors

In [24]:
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
tensor2 = torch.ones_like(tensor1)
tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
tensor_cat = torch.cat((tensor1, tensor2))
tensor_cat

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
torch.unbind(tensor_cat, dim=0)

(tensor([1., 2., 3.]),
 tensor([4., 5., 6.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]))

In [28]:
torch.unbind(tensor_cat, dim=1)

(tensor([1., 4., 1., 1.]), tensor([2., 5., 1., 1.]), tensor([3., 6., 1., 1.]))

In [29]:
torch.chunk(tensor_cat, 2, dim=0)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

#### Chunk retains dimension whereas unbind removed dimension

In [30]:
torch.chunk(tensor_cat, 2, dim=1)

(tensor([[1., 2.],
         [4., 5.],
         [1., 1.],
         [1., 1.]]),
 tensor([[3.],
         [6.],
         [1.],
         [1.]]))

In [31]:
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
tensor1.add(10)

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [33]:
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### "_" signifies in-place method

In [34]:
tensor1.add_(10)
tensor1

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [35]:
tensor1.sub_(5)
tensor1

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [36]:
tensor1.sqrt_()
tensor1

tensor([[2.4495, 2.6458, 2.8284],
        [3.0000, 3.1623, 3.3166]])

In [37]:
tensor_rand = torch.rand(3,3)
tensor_rand

tensor([[0.0253, 0.1398, 0.0787],
        [0.5082, 0.4503, 0.4650],
        [0.7049, 0.7086, 0.7713]])

#### Number of elements in a tensor

In [38]:
torch.numel(tensor_rand)

9

#### Size of a tensor

In [39]:
tensor_rand.size()

torch.Size([3, 3])

### Views

In [40]:
tensor_rand

tensor([[0.0253, 0.1398, 0.0787],
        [0.5082, 0.4503, 0.4650],
        [0.7049, 0.7086, 0.7713]])

In [41]:
tensor_rand[0:2, 1:]

tensor([[0.1398, 0.0787],
        [0.4503, 0.4650]])

In [42]:
tensor_rand[1:, 0:]

tensor([[0.5082, 0.4503, 0.4650],
        [0.7049, 0.7086, 0.7713]])

In [43]:
tensor_rand.view(9)

tensor([0.0253, 0.1398, 0.0787, 0.5082, 0.4503, 0.4650, 0.7049, 0.7086, 0.7713])

In [44]:
tensor_rand.view(6)

RuntimeError: shape '[6]' is invalid for input of size 9

In [45]:
tensor_rand.view(3,3,1)

tensor([[[0.0253],
         [0.1398],
         [0.0787]],

        [[0.5082],
         [0.4503],
         [0.4650]],

        [[0.7049],
         [0.7086],
         [0.7713]]])

In [46]:
tensor_1d = torch.Tensor([1,2,3])
tensor_1d

tensor([1., 2., 3.])

In [47]:
tensor_unsqueeze = torch.unsqueeze(tensor_1d, 1)
tensor_unsqueeze

tensor([[1.],
        [2.],
        [3.]])

In [48]:
tensor_unsqueeze = torch.unsqueeze(tensor_1d, 2)
tensor_unsqueeze

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [49]:
tensor_2d = torch.Tensor([[1,2], [3,4]])
tensor_2d

tensor([[1., 2.],
        [3., 4.]])

In [50]:
tensor_unsqueeze = torch.unsqueeze(tensor_2d, 1)
tensor_unsqueeze

tensor([[[1., 2.]],

        [[3., 4.]]])

In [51]:
tensor_unsqueeze = torch.unsqueeze(tensor_2d, 2)
tensor_unsqueeze

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

In [52]:
tensor_unsqueeze = torch.unsqueeze(tensor_2d, 3)
tensor_unsqueeze

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [53]:
tensor_squeeze = torch.squeeze(tensor_unsqueeze, 1)
tensor_squeeze

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

In [54]:
tensor_squeeze = torch.squeeze(tensor_unsqueeze, 2)
tensor_squeeze

tensor([[1., 2.],
        [3., 4.]])

In [55]:
tensor_transpose = torch.transpose(tensor_2d, dim0 = 0, dim1 = 1)
tensor_transpose

tensor([[1., 3.],
        [2., 4.]])

### More operations on tensors

In [56]:
tensor_rand

tensor([[0.0253, 0.1398, 0.0787],
        [0.5082, 0.4503, 0.4650],
        [0.7049, 0.7086, 0.7713]])

#### Sorting tensors

In [57]:
tensor_sorted, indices = torch.sort(tensor_rand, dim=0)
print(tensor_sorted)
print(indices)

tensor([[0.0253, 0.1398, 0.0787],
        [0.5082, 0.4503, 0.4650],
        [0.7049, 0.7086, 0.7713]])
tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])


In [58]:
tensor_sorted, indices = torch.sort(tensor_rand, dim=1)
print(tensor_sorted)
print(indices)

tensor([[0.0253, 0.0787, 0.1398],
        [0.4503, 0.4650, 0.5082],
        [0.7049, 0.7086, 0.7713]])
tensor([[0, 2, 1],
        [1, 2, 0],
        [0, 1, 2]])


In [59]:
tensor_negative = torch.Tensor([[-1, -2, -3], [-3, -4, -5]])
tensor_negative

tensor([[-1., -2., -3.],
        [-3., -4., -5.]])

In [60]:
tensor_positive = torch.abs(tensor_negative)
tensor_positive

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [61]:
torch.argmax(tensor_positive, dim=1)

tensor([2, 2])

In [62]:
torch.argmin(tensor_positive, dim=1)

tensor([0, 0])

### Matrix operations

In [63]:
tensor1

tensor([[2.4495, 2.6458, 2.8284],
        [3.0000, 3.1623, 3.3166]])

In [64]:
tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
tensor1 + 0.5

tensor([[2.9495, 3.1458, 3.3284],
        [3.5000, 3.6623, 3.8166]])

In [66]:
tensor1 + tensor2

tensor([[3.4495, 3.6458, 3.8284],
        [4.0000, 4.1623, 4.3166]])

In [67]:
tensor_added = torch.add(tensor1, tensor2)
tensor_added

tensor([[3.4495, 3.6458, 3.8284],
        [4.0000, 4.1623, 4.3166]])

In [68]:
tensor_div = torch.div(tensor2, tensor1)
tensor_div

tensor([[0.4082, 0.3780, 0.3536],
        [0.3333, 0.3162, 0.3015]])

In [69]:
tensor_mul = torch.mul(tensor1, tensor1)
tensor_mul

tensor([[ 6.0000,  7.0000,  8.0000],
        [ 9.0000, 10.0000, 11.0000]])

In [70]:
tensor1 * tensor1

tensor([[ 6.0000,  7.0000,  8.0000],
        [ 9.0000, 10.0000, 11.0000]])

tensor_1d

In [71]:
tensor_dot = torch.dot(tensor_1d, tensor_1d)
tensor_dot

tensor(14.)

In [72]:
tensor_matrix = torch.Tensor([[1, 2, 3], [4, 5, 6]])
tensor_matrix

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [73]:
tensor_vector = torch.Tensor([2, 2, 2])
tensor_vector

tensor([2., 2., 2.])

In [74]:
tensor_mv = torch.mv(tensor_matrix, tensor_vector)
tensor_mv

tensor([12., 30.])

In [75]:
tensor_matrix2 = torch.Tensor([[1, 1], [2, 2], [3, 3]])
tensor_matrix2

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [76]:
tensor_mm = torch.mm(tensor_matrix2, tensor_matrix)
tensor_mm

tensor([[ 5.,  7.,  9.],
        [10., 14., 18.],
        [15., 21., 27.]])

### NumPy & PyTorch Interoperability

In [77]:
import numpy as np

In [78]:
tensor1 = torch.rand(3,4)
tensor1

tensor([[0.9580, 0.5790, 0.6027, 0.0368],
        [0.1228, 0.9413, 0.5112, 0.1694],
        [0.1786, 0.1329, 0.0913, 0.0604]])

In [79]:
numpy_arr1 = tensor1.numpy()
numpy_arr1

array([[0.9580317 , 0.57897258, 0.60268312, 0.0367957 ],
       [0.12278081, 0.94130614, 0.51121273, 0.16939049],
       [0.17862741, 0.1328924 , 0.09131257, 0.06044054]])

In [80]:
torch.is_tensor(tensor1)

True

In [81]:
torch.is_tensor(numpy_arr1)

False

#### Remember: NumPy arrays & tensors share the same memory

In [82]:
tensor1.add_(10)
numpy_arr1

array([[10.9580317 , 10.57897258, 10.60268312, 10.0367957 ],
       [10.12278081, 10.94130614, 10.51121273, 10.16939049],
       [10.17862741, 10.1328924 , 10.09131257, 10.06044054]])

In [83]:
numpy_arr1[0, 0] = 100
tensor1

tensor([[100.0000,  10.5790,  10.6027,  10.0368],
        [ 10.1228,  10.9413,  10.5112,  10.1694],
        [ 10.1786,  10.1329,  10.0913,  10.0604]])

In [84]:
numpy_arr2 = np.array([[1, 2, 3], [3, 4, 5]], dtype=np.float64)
numpy_arr2

array([[1., 2., 3.],
       [3., 4., 5.]])

In [85]:
tensor_from_numpy = torch.from_numpy(numpy_arr2)
tensor_from_numpy

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [86]:
tensor_from_numpy.div_(10)
numpy_arr2

array([[0.1, 0.2, 0.3],
       [0.3, 0.4, 0.5]])

### CUDA

In [91]:
torch.cuda.is_available()

True

In [92]:
torch.cuda.current_device()

0

In [95]:
torch.cuda.get_device_name(0)

'GeForce GTX 1660 Ti'

In [96]:
torch.cuda.device_count()

1

In [97]:
torch.cuda.memory_allocated()

0

In [98]:
torch.cuda.memory_reserved()

0

#### Storing CUDA device object

In [99]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [100]:
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')

In [105]:
x = torch.Tensor([1,2])
x

tensor([1., 2.])

#### Passing "cuda" as device parameter picks the first available GPU

In [106]:
x = torch.tensor([1,2], device=cuda)
x

tensor([1, 2], device='cuda:0')

In [107]:
x_0 = torch.tensor([1,2], device=cuda0)
x_0

tensor([1, 2], device='cuda:0')

In [108]:
x_1 = torch.tensor([1,2], device=cuda1)
x_1

RuntimeError: CUDA error: invalid device ordinal

In [109]:
x = torch.Tensor([1, 2])
x

tensor([1., 2.])

In [110]:
x_cuda = x.cuda()
x_cuda

tensor([1., 2.], device='cuda:0')

In [111]:
x_cuda = x.to(device=cuda)
x_cuda

tensor([1., 2.], device='cuda:0')

In [114]:
x_cuda_sum = x_cuda + 5
x_cuda_sum

tensor([6., 7.], device='cuda:0')

In [115]:
torch.cuda.memory_allocated()

4096

In [116]:
torch.cuda.memory_reserved()

2097152

In [117]:
torch.cuda.empty_cache()